name: rapicredito
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  device_info_plus: ^9.0.2
  flutter_pickers: ^2.1.8
  permission_handler: ^10.3.0
  connectivity_plus: ^4.0.1
  get: ^4.6.5
  flutter_swiper_null_safety: ^1.0.2
  webview_flutter: ^4.2.2
  shared_preferences: ^2.1.2
  decimal: ^2.3.2
  pull_to_refresh: ^2.0.0
  cached_network_image: ^3.2.3
  timelines: ^0.1.0
  image_picker: ^0.8.9
  url_launcher: ^6.1.11
  json_serializable: ^6.2.0
  build_runner: ^2.1.0
  bot_toast: ^4.0.4
  dio: ^5.0.2
  http_proxy: ^1.2.1
  flutter_image_compress: ^2.0.4
  camera: ^0.10.5+3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true
  assets:
    - assets/image/
    - assets/image/main/
    - assets/image/splash/
    - assets/image/auth/
    - assets/image/login/